baseurl      = "https://sorodo.github.io/hugosorodo/"
title        = "My Blog"
languageCode = "zh-cn"
theme        = "hello-4s3ti"
paginate     = 10
defaultContentLanguage = "zh"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
IsMultiLingual = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "sorodo"

[params]
  dateform        = "Jan 2, 2006" 
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to sorodo's kitty room"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  backgroundImage  = "https://s3.bmp.ovh/imgs/2024/05/28/6cbf66f0685e40c5.jpg"
  backgroundEffects = true

  # Shows Posts on the front/Home page
  showPosts = true

  # Shows the ReadMore button in text instead
  ReadmoreText = true

  # Hides ReadMore
  hideReadMore = false

  # Shows reding time
  ShowReadingTime = true

  
  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    # Shows social icons on footer instead of main page
    socialIcons = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Hello 4s3ti theme by <a href=\"https://github.com/4s3ti\">4s3ti</a>"
    ]
    
  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  
  [params.portrait]
    path     = "https://s3.bmp.ovh/imgs/2024/05/28/0d526b71da9a5101.jpg"
    alt      = "Portrait"
    maxWidth = "50px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"
    icon = "fa-solid fa-envelope"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.zh]
    title = "sorodo猫娘"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.zh.params]
      subtitle = "喵喵喵"

    [languages.zh.params.logo]
      logoText = "只要足够可爱哪怕只会喵喵喵那也没问题吧"
      logoHomeLink = ""
      # logoCursorColor    = "#67a2c9"
      logoCursorAnimate  = "2s"
    # or
    #
    # path = "toux.svg"
    # alt = "Your example logo alt text"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "pixiv"
    name       = "Paint"
    url        = "/pixiv"