# 加到 config.toml 顶部（theme 配置之后）
ignoreFiles = ["themes/digio-theme/content/open-source/**", "themes/digio-theme/content/write/**"]

baseurl      = "https://sorodo.github.io/hugosorodo/"
title        = "Sorodo Research"
languageCode = "zh-cn"
theme        = "digio-theme"
paginate     = 10
defaultContentLanguage = "zh"

[author]
  name = "sorodo"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.zh]
    title = "Sorodo Research"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # And you can even create generic menu
  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "/research"

  [[menu.main]]
    identifier = "tech sharing"
    name       = "Tech Sharing"
    url        = "/tech-sharing"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

  [[menu.main]]
    identifier = "me"
    name       = "Me"
    url        = "/me"

  [[menu.main]]
    identifier = "HOME"
    name       = "HOME"
    url        = "/"
